MyApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('myapp.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

urlpatterns = [
    path('token/get/', TokenObtainPairView.as_view(), name='token_get'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('posts/own/', views.user_posts, name='own_posts'),
    path('posts/', views.posts, name='posts'),
    path('login/', views.LogInView.as_view(), name='api_login'),
    path('register/', views.register, name='api_register'),
    path('posts/add/', views.add_post, name='add_post'),
    path('posts/delete/<int:id>/', views.delete_post, name='delete_post'),
    path('posts/like/<int:id>/', views.like_post, name='like_post'),
    path('posts/dislike/<int:id>/', views.dislike_post, name='dislike_post'),
    path('posts/comments/get/<int:id>/', views.get_comments, name='get_comments'),
    path('posts/comments/add/<int:id>/', views.add_comment, name='add_comment')
]

myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('account/', views.account, name='account'),
    path('account/edit', views.edit_account, name='edit_account'),
    path('account/add_post', views.add_post, name='add_post'),
    path('show_post/<int:id>', views.show_post, name='show_post'),
    path('account/edit_post/<int:id>', views.edit_post, name='edit_post'),
    path('account/delete_photo/<int:id>', views.delete_photo, name='delete_photo'),
    path('account/delete_image/<int:post_id>/<int:img_id>', views.delete_image, name='delete_image'),
    path('account/delete_post/<int:id>', views.delete_post, name='delete_post'),
    path('search', views.search, name='search'),
    path('dislike/<int:post_id>', views.dislike_post, name='dislike_post'),
    path('like/<int:post_id>', views.like_post, name='like_post'),

]

myapp/models.py
import os

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    gender = models.CharField(max_length=10, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    emotions = models.TextField(max_length=1000, blank=True, null=True)
    photo = models.ImageField(upload_to='profile_photos/', blank=True, null=True, default='user_empty_photo.jpg')

    def set_image_to_default(self):
        os.remove(self.photo.path)
        self.photo = 'user_empty_photo.jpg'
        super(Profile, self).save()

    def __str__(self):
        return self.user.username


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, name='user', related_name='posts')
    title = models.CharField(max_length=200, default='', blank=True, null=True)
    text = models.TextField(max_length=30000)
    created_date = models.DateTimeField(default=timezone.now)
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, name='post', related_name='images')
    image = models.ImageField(upload_to='posts_images/', blank=True, null=True)

    def delete(self, *args, **kwargs):
        os.remove(self.image.path)
        super().delete(*args, **kwargs)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, name='user', related_name='comments', default=None)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, name='post', related_name='comments', default=None)
    text = models.TextField(max_length=3000)
    created_date = models.DateTimeField(default=timezone.now)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from .models import Profile, Post, Comment, Image


class CreateUser(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(CreateUser, self).save(commit=False)
        user.email = self.cleaned_data.get('email')
        if commit:
            user.save()
        return user


class EditUser(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
        )


class EditProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('city', 'gender', 'emotions', 'photo')


class AddPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'text',
        )


class ListingFormImage(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('image',)


class EditPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'text'
        )


class AddComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'text',
        )

myapp/views.py
from PIL import Image as Img
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, reverse

from .forms import CreateUser, EditUser, EditProfile, AddComment, AddPost, EditPost
from .models import Profile, Post, Image, Comment


def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                messages.success(request, 'You are logged in as {}'.format(username))
                return redirect('myapp:account')
            else:
                messages.error(request, 'Username or password is invalid')
        else:
            for message in form.error_messages:
                messages.error(request, '{}: {}'.format(message, form.error_messages[message]))
    form = AuthenticationForm
    return render(request, 'myapp/login.html', {'form': form})


def photo_resize(inst):
    image = Img.open(inst.photo)
    size = (300, 300)
    image.resize(size, Img.ANTIALIAS)
    image.save(inst.photo.path)
    inst.save()


def image_resize(inst):
    image = Img.open(inst.image)
    size = (300, 300)
    image.resize(size, Img.ANTIALIAS)
    image.save(inst.image.path)
    inst.save()


def home(request):
    posts = Post.objects.all().order_by('created_date')
    return render(request, 'myapp/home.html', {'posts': posts})


def logout_user(request):
    logout(request)
    messages.info(request, 'Logged out successfully')
    return redirect('myapp:home')


def register(request):
    form = CreateUser(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            users = User.objects.filter(username=form.data['username']).all()
            if users:
                messages.error(request, 'Usernsme already exists')
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, 'New account created: {}'.format(username))
            login(request, user)
            return redirect('myapp:edit_account')
        else:
            for message in form.error_messages:
                messages.error(request, '{}: {}'.format(message, form.error_messages[message]))
    return render(request=request,
                  template_name='myapp/register.html',
                  context={'form': form})


@login_required(login_url='/login')
def account(request):
    user = request.user
    posts = Post.objects.filter(user=user).all()
    return render(request, 'myapp/account.html', context={'user': user, 'posts': posts})


@login_required(login_url='/login')
def edit_account(request):
    form_user = EditUser(instance=request.user, data=request.POST or None)
    form_profile = EditProfile(instance=request.user.profile, files=request.FILES, data=request.POST or None)
    if form_user.is_valid() and form_profile.is_valid():
        if 'user_empty_photo' in form_profile.cleaned_data.get('photo'):
            form_profile.cleaned_data.pop('photo')
        form_user.save()
        profile = form_profile.save()
        if 'user_empty_photo' not in profile.photo.path:
            photo_resize(profile)
        messages.success(request, 'Information changed successfully')
        return redirect('myapp:account')
    return render(request=request,
                  template_name='myapp/edit_account.html',
                  context={'form_user': form_user, 'form_profile': form_profile})


@login_required(login_url='/login')
def add_post(request):
    form = AddPost(data=request.POST or None)
    if form.is_valid():
        post = Post(user=request.user, title=form.cleaned_data.get('title'), text=form.cleaned_data.get('text'))
        post.save()
        for file in request.FILES.getlist('images'):
            instance = Image(
                post=post,
                image=file
            )
            instance.save()
            image_resize(instance)
        return redirect('myapp:account')
    return render(request=request,
                  template_name='myapp/add_post.html',
                  context={'form': form})


@login_required(login_url='/login')
def edit_post(request, id):
    post = Post.objects.filter(user=request.user, pk=id).get()
    form = EditPost(instance=post, data=request.POST or None)
    if form.is_valid():
        form.save()
        for file in request.FILES.getlist('images'):
            instance = Image(
                post=post,
                image=file
            )
            instance.save()
            image_resize(instance)
            instance.save()
        return redirect('myapp:show_post', id=id)
    return render(request=request,
                  template_name='myapp/edit_post.html',
                  context={'form': form, 'post': post})


def show_post(request, id):
    user = request.user
    post = Post.objects.filter(pk=id).get()
    images = post.images.all()
    comments = Comment.objects.filter(post=post).all()
    form = AddComment(data=request.POST or None)
    if form.is_valid() and request.user.is_authenticated:
        comment = Comment(
            user=request.user,
            text=form.cleaned_data["text"],
            post=post
        )
        comment.save()
        return redirect(reverse('myapp:show_post', args=(post.pk,)))
    return render(request, 'myapp/show_post.html', context={'user': user, 'post': post, 'images': images,
                                                            'comments': comments, 'form': form})


@login_required(login_url='/login')
def delete_image(request, post_id, img_id):
    Image.objects.get(pk=img_id).delete()
    return redirect('myapp:edit_post', id=post_id)


@login_required(login_url='/login')
def delete_photo(request, id):
    profile = Profile.objects.get(pk=id)
    profile.set_image_to_default()

    return redirect('myapp:edit_account')


@login_required(login_url='/login')
def delete_post(request, id):
    post = Post.objects.get(pk=id)
    post.delete(keep_parents=True)
    return redirect('myapp:account')


@login_required(login_url='/login')
def like_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    if not request.user.is_authenticated:
        messages.error(request, 'Cannot score this post. Log in first!')
        return redirect(reverse('myapp:show_post', args=(post.pk,)))

    post.likes += 1
    post.save()
    return redirect(reverse('myapp:show_post', args=(post.pk,)))


@login_required(login_url='/login')
def dislike_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    if not request.user.is_authenticated:
        messages.error(request, 'Cannot score this post. Log in first!')
        return redirect(reverse('myapp:show_post', args=(post.pk,)))

    post.dislikes += 1
    post.save()
    return redirect(reverse('myapp:show_post', args=(post.pk,)))


def search(request):
    posts = Post.objects.all()
    query = request.GET['search'].lower()
    results = [post for post in posts if query in post.text.lower() or query in post.title.lower()]
    return render(request, 'myapp/post_template.html', context={'posts': results})

myapp/templates/myapp/account.html
{% extends 'index.html' %}

{% block head %}
    <title>Account</title>
{% endblock %}
{% block content %}
    <div class="row" style="width: 100%">
        <div class="sidebar inline float-left" style="width: 40%">
            <div class="card">
                {% include 'myapp/account_small.html' with objects=user %}
                <p style="padding: 5px; margin-left: 10px" class="card-text">{{ user.profile.emotions }}</p>
            </div>
        </div>
        <div class="main card" style="width: 50%">
            {% for post in posts %}
                {% include 'myapp/post_template_small.html' with objects=post %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/account_small.html
<img class="card-img-top" src="{{ user.profile.photo.url }}">
<div class="card-body">
    {% if user.first_name or user.last_name %}
        <h3>{{ user.first_name }} {{ user.last_name }}</h3>
    {% endif %}
    {% if user.profile.city %}
        <p class="card-text">{{ user.profile.city }}</p>
    {% endif %}
    {% if request.user.pk == user.pk and request.user.is_authenticated %}
        <a href="{% url 'myapp:edit_account' %}" class="btn btn-primary">Edit account</a>
        <a href="{% url 'myapp:add_post' %}" class="btn btn-primary">Add new post</a>
    {% endif %}
</div>

myapp/templates/myapp/add_post.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block head %}
    <title>Add post</title>
{% endblock %}
{% block content %}
    <br><br>
    <div class="container">
        <br>
        <div class="form-group">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="file" name="images">
                <button class="button btn-default" type="submit">Add</button>
            </form>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/edit_account.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block header %}
    <title>Edit account</title>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="container">
            <a href="{% url 'myapp:delete_photo' user.profile.pk %}"><img alt="Press to delete your photo"
                                                                          src="{{ user.profile.photo.url }}"
                                                                          class="img"></a>
            <div class="container">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form_user|crispy }}
                    {{ form_profile|crispy }}
                    <button type="submit" class="button btn-success">Change</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/edit_post.html
{% extends 'index.html' %}

{% block head %}
    <title>Edit post</title>
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <br><br>
    <div class="container">
        <br>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="file" name="images" multiple>
            <button type="submit" class="button btn-success">Change</button>
        </form>
        <div class="container">
            {% for image in post.images.all %}
                <a href="{% url 'myapp:delete_image' post.pk image.pk %}"><img src={{ image.image.url }}></a>
            {% endfor %}
        </div>
    </div>

{% endblock %}

myapp/templates/myapp/home.html
{% extends 'index.html' %}
{% block head %}
    <title>Home</title>
{% endblock %}
{% block content %}
    <div class="main">
        <div class="row">
            {% for post in posts %}
                <div class="col-md-12 inline">
                    {% include 'myapp/post_template_small.html' with objects=post %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/login.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block header %}
    <title>Login</title>
{% endblock %}
{% block content %}
    <h3>You can login here</h3>
    <div class="container">
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="button btn-success">Login</button>
            </form>

        </div>
    </div>
{% endblock %}

myapp/templates/myapp/post_template.html
{% extends 'index.html' %}
{% block head %}
    <title>Post</title>
{% endblock %}
{% block content %}
    <div class="row" style="width: 100%">
        {% if not posts %}
            <h3>Nothing found</h3>
        {% endif %}
        <div class="main card" style="width: 50%">
            {% for post in posts %}
                {% include 'myapp/post_template_small.html' with objects=post %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/post_template_small.html
<div class="container">
    <h3>{{ post.title }}</h3>
    {% if post.images.all %}
        <img class="img-thumbnail thumbnail rounded float-left" style="width: 30%; padding: 5px"
             src={{ post.images.all.0.image.url }}>
    {% endif %}
    {{ post.text|truncatewords:25 }} <a href="{% url 'myapp:show_post' post.pk %}">Read more...</a>
    <p>{{ post.created_date }}</p>
</div>

myapp/templates/myapp/register.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block header %}
    <title>Register</title>
{% endblock %}
{% block content %}
    <div class="container">
        <h3>You can register here</h3>
        <div class="container">
            <div class="form-group">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="button btn-success">Register</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

myapp/templates/myapp/show_post.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
    <div class="row-fluid">
        <h3>{{ post.title }}</h3>
        <div class="inline float-left" style="width: 40%">
            {% for image in images %}
                <div class="thumb">
                    <img class="img-rounded img-responsive img-thumbnail" style="width: 90%; padding: 5px"
                         src={{ image.image.url }}>
                </div>
            {% endfor %}
        </div>
        <div class="container">
            <p>{{ post.text }}</p>
            <p>{{ post.created_date }}</p>
            <br>
            <ul class="nav">
                {% if request.user.pk == post.user.pk %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:edit_post' post.pk %}">Edit post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'myapp:delete_post' post.pk %}">Delete post</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:like_post' post.pk %}"><img
                            src="../media/like.jpg"> {{ post.likes }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:dislike_post' post.pk %}"><img
                            src="../media/dislike.png"> {{ post.dislikes }}</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <h3>Comments:</h3>
            {% for comment in comments %}
                <div class="media">
                    <img src="{{ comment.user.profile.photo.url }}" class="align-self-start mr-3" style="width:60px">
                    <div class="media-body">
                        <p>{{ comment.user.username }}: {{ comment.created_date }}</p>
                        <p>{{ comment.text }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="container">
        <h3>Leave a comment:</h3>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Comment</button>
        </form>
    </div>
{% endblock %}